

services:
  fastapi:
    build: fastapi1/
    ports:
      - 8000:8000
    networks:
      - deploy_network
    container_name: fastapi

  streamlit:
    build: streamlit1/
    depends_on:
      - fastapi
    ports:
        - 80:80
    networks:
      - deploy_network
    container_name: streamlit

networks:
  deploy_network:
    driver: bridge